application: investmenttracker
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /cronUpdatePrices
  script: updatePrices.app

- url: /
  script: investmenttracker.app
libraries:
- name: jinja2
  version: latest
